apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition    # 自定义 k8s API resource
metadata:
  name: kasei.xxx.crds

spec:
  group: xxx.kaseihaku.com
  names:
    kind: AbcdEfg     #  CamelCase and singular
    listKind: AbcdEfgList   # 默认为 <kind>+List
    singular: abcdefg       # 当前 kind 的单数形式，默认为 <kind> 转小写
    plural: abcdefgs          # 当前 kind 的复数形式，必须是 lowercase
    shortNames:
      - a2g         # 必须小写
  scope: Namespaced     # [Cluster: 表示当前资源是集群层面的, Namespaced: 表示当前资源具有命名空间属性]
  # GA > beta > alpha    其中 GA 可以省略
  versions:
    - name: v1
      served: true    # 指定该 version 是否可以通过 REST API 访问
      storage: true   # 持久化该自定义资源时，是否带 version
      deprecated: false # 表示当前 version 过时
      deprecationWarning: deprecated description    # 过时描述


      # 该 version 字段模板
      schema:
        # $ 开头的都是 当前 schema 元数据
        #$schema: https://json-schema.org/draft/2020-12/schema    # 当前 schema 编写是基于哪个版本
        #$ref:


        # 使用 openAPIV3Schema 进行字段校验和修剪
        # http://json-schema.org/
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true   # schema 中没定义的 field 是否要保留，true=保留
          description: desc     # 当前 schema 描述
          # 可用值 = ["null", "boolean", "object", "array", "number", "string", "integer"]
          type: object      # 表示当前 层级 的数据类型
          enum: []    # 当前层级的 value 必须在 enum 中

          required: ['apiVersion', 'kind', 'metadata']  # 表示当前层级 JSON 对象(即: <properties> 中) 的指定属性 必填
          # 当 type=object 时，字段有哪些，格式怎么样
          properties:
            apiVersion:
              description: version
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                xxxArg:
                  type: array
          # 当 type=array 时，配置数组元素的类型
          # 可以是 JSONSchemaProps 或者 JSONSchemaPropsArray
          #   JSONSchemaProps: 所有数组元素只有一个类型
          #   JSONSchemaPropsArray: 数组元素可以有多个类型
          items:
            type: string
          # 当前 层级 默认值，如果没定义的话
          default: {}






