apiVersion: v1
kind: Secret    # 用于 k8s 中用于存放 密码，密钥，凭证 等敏感信息的对象
metadata:          
  name: secret
# Builtin Type:
#   Opaque: 任意用户定义数据
#   kubernetes.io/service-account-token: 
#   kubernetes.io/dockerconfigjson: base64 格式的 ~/.docker/config.json 内容
#   kubernetes.io/basic-auth: 
#   kubernetes.io/ssh-auth: 
#   kubernetes.io/tls: 
#   bootstrap.kubernetes.io/token: 
type: kubernetes.io/dockerconfigjson
# 该字段下所有的 value 都必须是 base64 编码的
data:
  # shell> cat ~/.docker/config.json | base64 -   # base64 encode
  .dockerconfigjson: |-
    "<base64 encoded ~/.docker/config.json file>"
# 与 ${data} 的区别是，该字段下的 value 不是 base64 编码的，
# 如果 key 在 ${data} 和 ${stringData} 同时出现，${stringData} 优先级高
stringData:
  key: kasei

# Secret 使用方式：
# 方式一：把 Secrets 当做 file 使用，随 Secret 的改变而改变
#   在 pod.yml 中配置一个 卷 {.spec.volumes[].secret.secretName}
#   然后把这个 卷 通过 name 绑定到 {.spec.containers[].volumeMounts[]} 上
# 方式二: 把 Secrets 当做 环境变量 使用，不会随 Secret 的改变而改变
#   {.spec.containers[].env[].valueFrom.secretKeyRef}
# 方式三: 在 Pod 中配置 {.spec.imagePullSecrets} 

immutable: true   # 配置当前 Secret 不可变
