version: '3.8'
services:
  v2fly:
    image: v2fly/v2fly-core:v4.45.2
    ports: [12345:12345,12346:12346]
    network_mode: host    # 必须是 host ，否则透明代理无效
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json:ro
    restart: always    # 自动启动
